Repository openshift/windows-machine-config-operator-fbc, pull requests merged in 2025-03, with the labels that each got.

#43 WINC-1362: Add FIPS check to pipeline
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-fbc-master-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-master-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-fbc-release-4-18-push.yaml
Labels: lgtm, jira/valid-reference, approved

#45 Update README
  README.md
Labels: lgtm, approved

#47 New 10.18 release from WMCO 414e210
  .tekton/images-mirror-set.yaml
  v10.18/catalog-template.json
  v10.18/catalog/windows-machine-config-operator/catalog.json
Labels: lgtm, approved

#51 Update image mirror sets for multiple release streams
  .tekton/images-mirror-set.yaml
Labels: lgtm, approved

#50 Add catalog linting and clarify README
  README.md
  lint.sh
Labels: lgtm, needs-rebase, approved
